project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://giulioorazzo.github.io/STA-9713/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: superhero
    toc: false

editor:
  mode: source